Category.create(category_id: nil, name: 'Shirts')
  Category.create(category_id: 1, name: 'Dress Shirts')
  Category.create(category_id: 1, name: 'T-Shirts')
  Category.create(category_id: 1, name: 'Polos')
Category.create(category_id: nil, name: 'Pants')
  Category.create(category_id: 5, name: 'Jeans')
  Category.create(category_id: 5, name: 'Dress Pants')
Category.create(category_id: nil, name: 'Underwear')
  Category.create(category_id: 8, name: 'Briefs')
  Category.create(category_id: 8, name: 'Boxer-Briefs')
  Category.create(category_id: 8, name: 'Boxers')
Category.create(category_id: nil, name: 'Shoes')
  Category.create(category_id: 12, name: 'Dress Shoes')
  Category.create(category_id: 12, name: 'Running Shoes')
  Category.create(category_id: 12, name: 'Slippers')
Category.create(category_id: nil, name: 'Accessories')
  Category.create(category_id: 16, name: 'Watches')

Product.create(category_id: 1, name: 'Galaxy S2', image: 'galaxys2.png', price: '599.99', manufacturer: 'Samsung', quantity: 3, description: 'Smartphone')
