Category.create(category_id: nil, name: 'Shirts')
  Category.create(category_id: 1, name: 'Dress Shirts')
  Category.create(category_id: 1, name: 'T-Shirts')
  Category.create(category_id: 1, name: 'Polos')
Category.create(category_id: nil, name: 'Pants')
  Category.create(category_id: 5, name: 'Jeans')
  Category.create(category_id: 5, name: 'Dress Pants')
Category.create(category_id: nil, name: 'Underwear')
  Category.create(category_id: 8, name: 'Briefs')
  Category.create(category_id: 8, name: 'Boxer-Briefs')
  Category.create(category_id: 8, name: 'Boxers')
Category.create(category_id: nil, name: 'Shoes')
  Category.create(category_id: 12, name: 'Dress Shoes')
  Category.create(category_id: 12, name: 'Running Shoes')
  Category.create(category_id: 12, name: 'Slippers')
Category.create(category_id: nil, name: 'Accessories')
  Category.create(category_id: 16, name: 'Watches')

Slider.create(title: 'Slider 1', text: 'Forest Trail', image: '1.jpg', link: '/')
Slider.create(title: 'Slider 2', text: 'Moonlit Road', image: '2.jpg', link: '/')
Slider.create(title: 'Slider 3', text: 'Moss-covered Bridge', image: '3.jpg', link: '/')

Brand.create(name: 'Emporio Armani')
Brand.create(name: 'Hurley')

Product.create(category_id: 2, brand_id: 1, name: 'Slim Fit Shirt in Stretch Cotton Poplin', image: '38389881bd.jpg', price: '507.00', quantity: 1, description: 'Composition: 78% Cotton, 28% Polyamide, 2% Elastane')
Product.create(category_id: 6, brand_id: 1, name: 'Slim Fit Low Rise Jeans', image: '36553289ma.jpg', price: '410.00', quantity: 3, description: 'Composition: 98% Cotton, 2% Elastane')
Product.create(category_id: 17, brand_id: 1, name: 'Watch Swiss Made Collection', image: '50154747su.jpg', price: '632.00', quantity: 2, description: '40mm case. Sunray finish on the case. Cabochon in smoky quartz.')
Product.create(category_id: 7, brand_id: 1, name: 'Pinstripe Wool Trousers', image: '36555583lr.jpg', price: '670.00', quantity: 2, description: 'Composition: 100% Virgin Wool')
Product.create(category_id: 3, brand_id: 1, name: 'Crew Neck T-shirt in Cotton Pique', image: '37578693WT.jpg', price: '237.00', quantity: 4, description: 'Composition: 100% Cotton')
Product.create(category_id: 2, brand_id: 1, name: 'Jersey Shirt with Shawl Collar', image: '38389895EI.jpg', price: '410.00', quantity: 2, description: 'Composition: 100% Cotton')
Product.create(category_id: 3, brand_id: 2, name: 'One & Only Push Thru', image: 'MTS0008680.jpg', price: '25.00', quantity: 2, description: 'Color: Heather Black')

Discount.create(product_id: 1, value: 20.00, discount_type: '%', start_date: '2014-07-20 12:01:00', end_date: '2014-07-30 00:01:00')
Discount.create(product_id: 3, value: 33.00, discount_type: '%', start_date: '2014-07-20 12:01:00', end_date: '2014-07-30 00:01:00')
Discount.create(product_id: 7, value: 10.00, discount_type: '$', start_date: '2014-07-20 12:01:00', end_date: '2014-07-30 00:01:00')
